CREATE TABLE [datasets] (
  [id] int PRIMARY KEY IDENTITY(1, 1),
  [history] int,
  [cityID] int,
  [descriptions] nvarchar(255),
  [link] nvarchar(255),
  [name] nvarchar(255)
)
GO

CREATE TABLE [cities] (
  [id] int PRIMARY KEY,
  [name] nvarchar(255)
)
GO

ALTER TABLE [datasets] ADD FOREIGN KEY ([link]) REFERENCES [cities] ([id])
GO


--insert etme işlemi

INSERT INTO datasets VALUES('1','1839','34','Tanzimat Fermanı, Türk tarihinde Batılılaşmanın ilk somut adımıdır. 3 Kasım 1839'da Sultan Abdülmecid döneminde Hariciye Nazırı Koca Mustafa Reşid Paşa tarafından okunmuştur. Gülhane Parkı'nda okunması nedeniyle Gülhane Hatt-ı Şerifi (Padişah Yazısı), Gülhane Hatt-ı Hümâyûnu veya Tanzimât-ı Hayriye (Hayırlı Düzenlemeler) olarak da anılır. Bu fermanla devlet kendisini yenilemesi gerektiğini söylemiştir. Fransız İhtilâli ile Osmanlı ülkesinde aydın kişiler ve yeni fikirler oluşmaya başlamıştır. Özellikle meşrutî yönetim yanlısı aydınların baskıları, yapılan ıslahatların kalıcı olması fikri ve Fransız İhtilâli ile ülkeye giren milliyetçilik fikirlerinin olumsuz etkilerinden kurtulmak amacı ile 3 Kasım 1839 tarihinde Gülhane Parkı'nda ilan edilmiştir.','https://tr.wikipedia.org/wiki/Tanzimat_Fermanı','Tanzimat fermanı')
INSERT INTO datasets VALUES('2','1856','34','Islahat Fermanı veya Islâhat Hatt-ı Hümâyûnu Tanzimat’ın ilanından sonraki uygulamalarla ilgili olarak özellikle gayrimüslimlere yeni haklar tanıyan 18 Şubat 1856 tarihli hatt-ı hümâyun.','https://tr.wikipedia.org/wiki/Islahat_Fermanı','Islahat fermanı')
INSERT INTO datasets VALUES('3','1876','34','Kanun-ı Esasi[1] (Osmanlı Türkçesi: قانون اساسى) veya 1876 Anayasası, Kânûn-ı Esâsî çeviri olarak "temel kanun" ya da "anayasa" anlamına gelmektedir. Osmanlı İmparatorluğu'nun ilk ve son anayasasıdır. 23 Aralık 1876'da ilan edilmiş, 1878'de II. Abdülhamid tarafından askıya alınmış, 24 Temmuz 1908 ihtilali sonucunda yeniden yürürlüğe girmiştir. 1921 Anayasası'nın (Teşkîlât-ı Esâsîye Kanunu) kabul edildiği 20 Ocak 1921 tarihi ile 1924 Anayasası'nın yürürlüğe girdiği 24 Mayıs 1924 tarihi arasında ise kısmen yürürlükte kalmıştır.','https://tr.wikipedia.org/wiki/Kânûn-ı_Esâsî','Kanun-i esasi')
"INSERT INTO datasets VALUES('4','1878','34','Padişah II. Abdülhamit 1877-1878 Osmanlı Rus Savaşı 
devam ederken Kanun-ı Esasi’nin kendisine verdiği hakla Meclisi süresiz kapattı','https://tr.wikipedia.org/wiki/Meclis-i_Mebûsan','meclisi mebusanın kapatlması')"
INSERT INTO datasets VALUES('5','1908','34','İkinci Meşrutiyet (Osmanlıca: ايکنجى مشروطيت), Osmanlı Anayasası'nın, 30 yıl askıda kaldıktan sonra, 23 Temmuz 1908'de yeniden ilan edilmesiyle başlayan ve Mebuslar Meclisi'nin Sultan Vahdettin tarafından 11 Nisan 1920'de tasfiyesi ile sona eren dönemdir. Bu dönemde parlamenter demokrasi, seçim, siyasi parti, askerî darbe ve diktatörlük olgularıyla tanışılmış, iki büyük savaş (Balkan Savaşları ve I. Dünya Savaşı) yaşanmış ve imparatorluğun dağılmasına tanık olunmuştur.','https://tr.wikipedia.org/wiki/İkinci_Meşrutiyet','İkinci meşrutiyet')
"INSERT INTO datasets VALUES('6','1909','34','31 Mart Vakası (Kalkışması, İsyanı, Ayaklanması, Olayı yahut Hadisesi), II. Meşrutiyet'in ilanından sonra İstanbul'da yönetime karşı yapılmış büyük bir ayaklanma ve darbe teşebbüsüdür. Rumî Takvim'e göre 31 Mart 1325'te (13 Nisan 1909) başladığı için bu adla anılmıştır.

On üç gün süren ayaklanma, II. Meşrutiyet döneminin en önemli olaylarından biri olarak kabul edilir.[2] Askerî bir isyan olarak ortaya çıkmasına rağmen isyana dahil olan softaların propagandaları sonucu sonradan dinî bir hal almıştır.[3] Sebepleri tam olarak belirlenemeyen bu olayın planlı ve bilinçli bir hareket olup olmadığı kesinlik kazanmamıştır.[2][4] İsyanın ilk günü hükûmet istifa etmiş, isyancı askerler yedi gün süre ile İstanbul'a hakim olmuştur.','https://tr.wikipedia.org/wiki/31_Mart_Vakası','31 Mart vakası')"
INSERT INTO datasets VALUES('7','1913','22','İkinci Balkan Savaşı (Rumence: Al doilea război balcanic, Sırpça: Други балкански рат, Drugi balkanski rat, Yunanca: Δεύτερος Βαλκανικός Πόλεμος, Devteros Valkanikós Pólemos, Bulgarca: Междусъюзническата война, Mezhdusayuznicheskata voyna) I. Balkan Savaşı'na katılan devletlerin, Yunanistan Krallığı, Bulgaristan Krallığı, Karadağ Krallığı, Arnavutluk Krallığı, Sırbistan Krallığı, Osmanlı İmparatorluğu ve sonradan katılan Romanya Krallığı'nın aralarında yaptıkları savaşlardır. Bu savaş ile Edirne ve Kırklareli, Osmanlı'nın eline geçmiştir. Londra Konferansı'nın hükümleri kısmen değişmiştir.','https://tr.wikipedia.org/wiki/İkinci_Balkan_Savaşı','2. balkan savaşı')
"INSERT INTO datasets VALUES('8','1881','34','Düyun-u Umumiye (Düyun-u Umumiye-i Osmaniye Varidat-ı Muhassasa İdaresi), 1881-1923 yılları arasında Osmanlı İmparatorluğu'nun iç ve dış borçlarını denetleyen kurumdur.

II. Abdülhamit döneminde kurulmuştur. Sözcük, ""Genel Borçlar"" anlamına gelir. Düyun-u Umumiye kurulduğu yıldan itibaren, Osmanlı İmparatorluğu'nun ekonomik ve mali yaşamı üzerinde etkili bir rol oynamıştır.','https://tr.wikipedia.org/wiki/Düyûn-ı_Umûmiye','Düyûn-ı Umûmiye')"
INSERT INTO datasets VALUES('9','1914','34','Osmanlı hükümeti aslında tarafsız kalmak niyetindeydi. Ancak 10 Ağustos 1914’te Akdeniz’de İngiliz donanmasının takibinden kaçan Goeben ve Breslau adlı Alman kruvazörleri Çanakkale Boğazı’na girerek Osmanlı Devleti’ne sığındılar. ','https://islamansiklopedisi.org.tr/birinci-dunya-savasi','Osmnalınn birinci dünya savaşına katılması')
INSERT INTO datasets VALUES('10','1914','36','Kafkasya Cephesi, I. Dünya Savaşı'nda Osmanlı İmparatorluğu'nun 2. ve 3. orduları ile Rus İmparatorluğu Kafkas Ordusu'nun karşı karşıya geldikleri cephe. Kafkasya Cephesi, savaş sırasında Doğu Anadolu Bölgesi içlerine kadar genişlemiş, Trabzon, Bitlis, Muş ve Van şehirlerine kadar yayılmıştır. Kara harbi, Karadeniz Bölgesinde bulunan Osmanlı İmparatorluğu deniz gücü ve Rus donanması tarafından desteklenmiştir.','https://tr.wikipedia.org/wiki/Kafkasya_Cephesi','Kafkas Cephesi')
INSERT INTO datasets VALUES('11','1914','75','Kafkasya Cephesi, I. Dünya Savaşı'nda Osmanlı İmparatorluğu'nun 2. ve 3. orduları ile Rus İmparatorluğu Kafkas Ordusu'nun karşı karşıya geldikleri cephe. Kafkasya Cephesi, savaş sırasında Doğu Anadolu Bölgesi içlerine kadar genişlemiş, Trabzon, Bitlis, Muş ve Van şehirlerine kadar yayılmıştır. Kara harbi, Karadeniz Bölgesinde bulunan Osmanlı İmparatorluğu deniz gücü ve Rus donanması tarafından desteklenmiştir.','https://tr.wikipedia.org/wiki/Kafkasya_Cephesi','Kafkas Cephesi')
INSERT INTO datasets VALUES('12','1914','36','Sarıkamış Harekâtı, I. Dünya Savaşı sırasında, 22 Aralık 1914 ve 6 Ocak 1915 arasında Osmanlı İmparatorluğu ile Rus İmparatorluğu arasında Sarıkamış ve çevresinde (Oltu, Narman, Penek, Horasan, Bardız, Mecingirt, Karaurgan, Divik) gerçekleşen muharebeler olup Osmanlı İmparatorluğu'nun askeri taktik hatalarıyla başarısızlıkla sonuçlanan bir askeri girişimdir.','https://tr.wikipedia.org/wiki/Sarıkamış_Harekâtı','Sarıkamş harekatı')
INSERT INTO datasets VALUES('13','1916','25','Savaşların en trajik sonuçlarının başında, savaş bölgelerinde yaşayan sivil halkın yaşadığı bölgeleri terk etmeleri yani göçler gelmektedir. Birinci Dünya Savaşı’nda Kafkas Cephesi’nde yaşanan savaşlar ile muhaceret bölgenin kaderini derinden etkiledi. 1914 yılında savaşın ilk günlerinde başlayan muhaceret 1917 yılına kadar aralıksız olarak devam etti. Türk-Rus mücadelesinin yaşandığı bölgedeki Müslüman ahali Rus ilerlemesine paralel olarak sürekli batıya doğru göç etmek zorunda kaldı 1916 yılında Erzurum’un Rus işgaline uğramasının ardından göç eden insan sayısı doruk noktaya ulaştı. Türk ordusu geri çekilirken cephane ve ikmal araçlarını nakletmek için sivil halkın elindeki araçlara el koymuştu. ','https://www.idealonline.com.tr/IdealOnline/lookAtPublications/paperDetail.xhtml?uId=48060','Rus işgali')
INSERT INTO datasets VALUES('14','1916','49','Savaşların en trajik sonuçlarının başında, savaş bölgelerinde yaşayan sivil halkın yaşadığı bölgeleri terk etmeleri yani göçler gelmektedir. Birinci Dünya Savaşı’nda Kafkas Cephesi’nde yaşanan savaşlar ile muhaceret bölgenin kaderini derinden etkiledi. 1914 yılında savaşın ilk günlerinde başlayan muhaceret 1917 yılına kadar aralıksız olarak devam etti. Türk-Rus mücadelesinin yaşandığı bölgedeki Müslüman ahali Rus ilerlemesine paralel olarak sürekli batıya doğru göç etmek zorunda kaldı 1916 yılında Erzurum’un Rus işgaline uğramasının ardından göç eden insan sayısı doruk noktaya ulaştı. Türk ordusu geri çekilirken cephane ve ikmal araçlarını nakletmek için sivil halkın elindeki araçlara el koymuştu. ','https://www.idealonline.com.tr/IdealOnline/lookAtPublications/paperDetail.xhtml?uId=48060','Rus işgali')
INSERT INTO datasets VALUES('15','1916','13','Savaşların en trajik sonuçlarının başında, savaş bölgelerinde yaşayan sivil halkın yaşadığı bölgeleri terk etmeleri yani göçler gelmektedir. Birinci Dünya Savaşı’nda Kafkas Cephesi’nde yaşanan savaşlar ile muhaceret bölgenin kaderini derinden etkiledi. 1914 yılında savaşın ilk günlerinde başlayan muhaceret 1917 yılına kadar aralıksız olarak devam etti. Türk-Rus mücadelesinin yaşandığı bölgedeki Müslüman ahali Rus ilerlemesine paralel olarak sürekli batıya doğru göç etmek zorunda kaldı 1916 yılında Erzurum’un Rus işgaline uğramasının ardından göç eden insan sayısı doruk noktaya ulaştı. Türk ordusu geri çekilirken cephane ve ikmal araçlarını nakletmek için sivil halkın elindeki araçlara el koymuştu. ','https://www.idealonline.com.tr/IdealOnline/lookAtPublications/paperDetail.xhtml?uId=48060','Rus işgali')
INSERT INTO datasets VALUES('16','1916','61','Savaşların en trajik sonuçlarının başında, savaş bölgelerinde yaşayan sivil halkın yaşadığı bölgeleri terk etmeleri yani göçler gelmektedir. Birinci Dünya Savaşı’nda Kafkas Cephesi’nde yaşanan savaşlar ile muhaceret bölgenin kaderini derinden etkiledi. 1914 yılında savaşın ilk günlerinde başlayan muhaceret 1917 yılına kadar aralıksız olarak devam etti. Türk-Rus mücadelesinin yaşandığı bölgedeki Müslüman ahali Rus ilerlemesine paralel olarak sürekli batıya doğru göç etmek zorunda kaldı 1916 yılında Erzurum’un Rus işgaline uğramasının ardından göç eden insan sayısı doruk noktaya ulaştı. Türk ordusu geri çekilirken cephane ve ikmal araçlarını nakletmek için sivil halkın elindeki araçlara el koymuştu. ','https://www.idealonline.com.tr/IdealOnline/lookAtPublications/paperDetail.xhtml?uId=48060','Rus işgali')
INSERT INTO datasets VALUES('17','1916','69','Savaşların en trajik sonuçlarının başında, savaş bölgelerinde yaşayan sivil halkın yaşadığı bölgeleri terk etmeleri yani göçler gelmektedir. Birinci Dünya Savaşı’nda Kafkas Cephesi’nde yaşanan savaşlar ile muhaceret bölgenin kaderini derinden etkiledi. 1914 yılında savaşın ilk günlerinde başlayan muhaceret 1917 yılına kadar aralıksız olarak devam etti. Türk-Rus mücadelesinin yaşandığı bölgedeki Müslüman ahali Rus ilerlemesine paralel olarak sürekli batıya doğru göç etmek zorunda kaldı 1916 yılında Erzurum’un Rus işgaline uğramasının ardından göç eden insan sayısı doruk noktaya ulaştı. Türk ordusu geri çekilirken cephane ve ikmal araçlarını nakletmek için sivil halkın elindeki araçlara el koymuştu. ','https://www.idealonline.com.tr/IdealOnline/lookAtPublications/paperDetail.xhtml?uId=48060','Rus işgali')
INSERT INTO datasets VALUES('18','1916','65','Savaşların en trajik sonuçlarının başında, savaş bölgelerinde yaşayan sivil halkın yaşadığı bölgeleri terk etmeleri yani göçler gelmektedir. Birinci Dünya Savaşı’nda Kafkas Cephesi’nde yaşanan savaşlar ile muhaceret bölgenin kaderini derinden etkiledi. 1914 yılında savaşın ilk günlerinde başlayan muhaceret 1917 yılına kadar aralıksız olarak devam etti. Türk-Rus mücadelesinin yaşandığı bölgedeki Müslüman ahali Rus ilerlemesine paralel olarak sürekli batıya doğru göç etmek zorunda kaldı 1916 yılında Erzurum’un Rus işgaline uğramasının ardından göç eden insan sayısı doruk noktaya ulaştı. Türk ordusu geri çekilirken cephane ve ikmal araçlarını nakletmek için sivil halkın elindeki araçlara el koymuştu. ','https://www.idealonline.com.tr/IdealOnline/lookAtPublications/paperDetail.xhtml?uId=48060','Rus işgali')
INSERT INTO datasets VALUES('19','1916','24','Savaşların en trajik sonuçlarının başında, savaş bölgelerinde yaşayan sivil halkın yaşadığı bölgeleri terk etmeleri yani göçler gelmektedir. Birinci Dünya Savaşı’nda Kafkas Cephesi’nde yaşanan savaşlar ile muhaceret bölgenin kaderini derinden etkiledi. 1914 yılında savaşın ilk günlerinde başlayan muhaceret 1917 yılına kadar aralıksız olarak devam etti. Türk-Rus mücadelesinin yaşandığı bölgedeki Müslüman ahali Rus ilerlemesine paralel olarak sürekli batıya doğru göç etmek zorunda kaldı 1916 yılında Erzurum’un Rus işgaline uğramasının ardından göç eden insan sayısı doruk noktaya ulaştı. Türk ordusu geri çekilirken cephane ve ikmal araçlarını nakletmek için sivil halkın elindeki araçlara el koymuştu. ','https://www.idealonline.com.tr/IdealOnline/lookAtPublications/paperDetail.xhtml?uId=48060','Rus işgali')
INSERT INTO datasets VALUES('20','1916','13','Bitlis ilk olarak 2-3 Mart'ta Rusya İmparatorluk Kara Kuvvetleri'nin 2. Kafkas Kolordusu tarafından düşürüldü. Ancak 1 Ağustos'ta taarruza geçen Mirliva Mustafa Kemal Paşa komutasındaki Osmanlı 16. Kolordusu, Diyarbekir'e doğru ilerlemekte olan Nikolay Yudeniç komutasındaki Kafkas Ordusu'nu geri çevirerek 8 Ağustos'ta 5. Fırka ile Bitlis'i, 8. Fırka ile Muş'u geri aldı.[1]','https://tr.wikipedia.org/wiki/Bitlis_Muharebesi#:~:text=Kafkas%20Kolordusu%20tarafından%20düşürüldü.,ile%20Muş%27u%20geri%20aldı.','Bitlis'in geri alınması')
INSERT INTO datasets VALUES('21','1916','49','Bitlis ilk olarak 2-3 Mart'ta Rusya İmparatorluk Kara Kuvvetleri'nin 2. Kafkas Kolordusu tarafından düşürüldü. Ancak 1 Ağustos'ta taarruza geçen Mirliva Mustafa Kemal Paşa komutasındaki Osmanlı 16. Kolordusu, Diyarbekir'e doğru ilerlemekte olan Nikolay Yudeniç komutasındaki Kafkas Ordusu'nu geri çevirerek 8 Ağustos'ta 5. Fırka ile Bitlis'i, 8. Fırka ile Muş'u geri aldı.[1]','https://tr.wikipedia.org/wiki/Bitlis_Muharebesi#:~:text=Kafkas%20Kolordusu%20tarafından%20düşürüldü.,ile%20Muş%27u%20geri%20aldı.','Muş'un geri alınması')
INSERT INTO datasets VALUES('22','1917','24','Rusya; Osmanlı Devleti ile ilk olarak Erzincan Mütarekesi’ni imzalamıştır. 15 Aralık 1917 tarihinde imzalanan Antlaşma ile Rusya İmparatorluğu’na bağlı birlikler silah bırakarak; iç karışıklıklarına yönelmişlerdir.','https://antlasmalar.com/erzincan-mutarekesi/','Erzincan antlaşması ')
INSERT INTO datasets VALUES('23','1915','1','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('24','1915','6','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('25','1915','9','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('26','1915','11','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('27','1915','21','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('28','1915','31','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('29','1915','25','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('30','1915','26','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('31','1915','28','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('32','1915','35','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('33','1915','41','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('34','1915','38','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('35','1915','40','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('36','1915','42','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('37','1915','43','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('38','1915','46','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('39','1915','52','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('40','1915','58','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('41','1915','61','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('42','1915','66','Tehcir Kanunu veya resmî adıyla Sevk ve İskân Kanunu,[1][2] 27 Mayıs 1915'te Osmanlı Hükûmeti tarafından I. Dünya Savaşı'nda Osmanlı ordusu ile karşı karşıya gelebilecek iç unsurların savaş bölgelerinden uzak yerlere devlet eliyle gönderilmesi için çıkarılan göç kanunu. 1 Haziran 1915 tarihinde Takvim-i Vekâyi'de yayımlanarak yürürlüğe girdi.','https://tr.wikipedia.org/wiki/Tehcir_Kanunu','Tehcir Kanunu')
INSERT INTO datasets VALUES('43','1918','34','I. Dünya Savaşı'nın sona ermesinin ardından Osmanlı Hükümeti yer değiştirmeye tabi tutulan Ermenilerden isteyenlerin tekrar eski yerlerine iade edilmeleri için bir kararname çıkarmıştır. 4 Ocak 1919'da İçişleri Bakanı Mustafa Paşa'nın Başbakanlığa gönderdiği yazıda, Ermenilerden dönmek isteyenlerin eski yerlerine nakledilmeleri konusunda ilgili yerlere emir verildiği ve gereken önlemlerin alındığı belirtilmektedir6. Hükümetin hazırladığı 31 Aralık 1918 tarihli dönüş kararnamesi şöyledir:','https://dls-int.net/yerleri-de-i-tirilen-ermenilerin-geri-getirilmesi.html','Yerleri Değiştirilen Ermenilerin Geri Getirilmesi')
INSERT INTO datasets VALUES('44','1915','17','Çaakkale Zaferiyle ilgili ayrıntılı bilgi için butona tıklayınız','http://dunyasavasi.ttk.gov.tr/tr/canakkale-savaslari/','Çanakkale Zaferi')
INSERT INTO datasets VALUES('45','1918','34','Demirli savaş gemilerinin arasından geçerek ilerleyen istimbotta bulunan üzüntü içinde ağlayan Mustafa Kemal Atatürk’ün yaveri Cevad Abbas’a Mustafa Kemal Atatürk “Geldikleri Gibi Giderler!” sözünü söyler. Bu söz Kurtuluş Savaşı’mızın ilk işareti olur.','http://www.istanbul.gov.tr/milli-mucadelenin-denizdeki-sembolu-kartal-istimbotu#:~:text=Demirli%20savaş%20gemilerinin%20arasından%20geçerek,Savaşı%27mızın%20ilk%20işareti%20olur.','Geldikleri gibi giderler')
INSERT INTO datasets VALUES('46','1919','35','İzmir'in İşgali, I. Dünya Savaşı sonrasında Paris'te toplanan uluslararası barış konferansının kararıyla[kaynak belirtilmeli] İzmir kentinin 15 Mayıs 1919'da Yunanistan Krallığı tarafından işgaliyle başlayan ve 9 Eylül 1922'de Türk ordusunun kente girmesiyle sona eren işgaldir.[5]','https://tr.wikipedia.org/wiki/İzmir%27in_İşgali','İzmir'in işgali')
INSERT INTO datasets VALUES('47','1919','25','Ağustos 1919 tarihinde, Erzurum merkezli kurulmuştur. Elazığ'da da şubesi vardır. Bu cemiyet, önce İstanbul’da kurulmuş olan Vilayat-ı Şarkiye Müdafaa-i Hukuk-u Milliye Cemiyetine bağlı olarak açılmış, daha sonra Şarkî Anadolu Müdafaa-i Hukuk Cemiyeti adı ile İstanbul’dan ayrılmış, doğuda müdafaa-i hukuk akımını temsil ederek Mustafa Kemal’in sevk ve idaresinde güçlenmiş, bütün memlekete yayılacak bir program hazırlamıştır. Ayrıca bu dernek Erzurum kongresini toplayarak tüm yurdun savunulmasını kararlaştırmıştır.','https://tr.wikipedia.org/wiki/Şarkî_Anadolu_Müdâfaa-i_Hukuk_Cemiyeti','Şarkî Anadolu Müdafaa-i Hukuk Cemiyeti')
INSERT INTO datasets VALUES('48','1919','35','İzmir Müdâfaa-i Hukuku Osmaniye Cemiyeti, Moralızade Halit ve Nail Beyler ile arkadaşlarınca kuruldu. Ama İttihat ve Terakki'nin güçlü olduğu merkezlerden biri olan İzmir'de Mondros Mütarekesi'nin hemen ardından örgütlenmeye gidilmesi sakıncalı bulunabileceği için, kuruluş bildirgesi ancak 1 Aralık'ta vilayete verilebildi. Örgütün etkin bir yapıya kavuşması, Nurettin Paşa'nın İzmir'e vali olarak atanmasından sonra gerçekleşti. Ocak 1919'da bu dönemde kurulmuş bir başka örgüt olan Heyet-i İlmiye ile birleşti.','https://tr.wikipedia.org/wiki/İzmir_Müdâfaa-i_Hukuku_Osmaniye_Cemiyeti','İzmir Müdâfaa-i Hukuku Osmaniye Cemiyeti')
INSERT INTO datasets VALUES('49','1918','22','Trakya-Paşaeli Müdafaa-i Hukuk Cemiyeti, 30 Kasım 1918 tarihinde Edirne'de kurulan Türk Ulusal Hareketi yanlısı cemiyet.','https://tr.wikipedia.org/wiki/Trakya-Paşaeli_Müdâfaa-i_Hukuk_Cemiyeti','Trakya Paşaeli Müdafaa-i Hukuk Cemiyeti')
INSERT INTO datasets VALUES('50','1918','61','rabzon Muhafaza-i Hukuku Milliye Cemiyeti, 12 Şubat 1919'da Merkezi Trabzon olarak kurulan cemiyet, Karadeniz Bölgesi'nin çeşitli il ve ilçelerinde şubeler açtı. Amacı, Trabzon ve çevresinin Rumlara verilmesini ve bir Pontus Devletinin kurulmasını önlemekti. Bu yörede faaliyet gösteren Etniki Eterya Cemiyeti ile mücadele eden bu teşkilat, Erzurum Kongresi’nden sonra Şarkî Anadolu Müdafaa-i Hukuk Cemiyeti’nin şubesi haline gelmiştir.','https://tr.wikipedia.org/wiki/Trabzon_Muhafaza-i_Hukuku_Milliye_Cemiyeti','Trabzon Muhafaza-i Hukuku Milli Cemiyeti')
INSERT INTO datasets VALUES('51','1918','1','Kilikyalılar Cemiyeti, 1918'de İstanbul'da kurulmuştur. Amacı, Kilikya (Çukurova) bölgesinin Fransızlar ve Ermeniler tarafından işgal edilmesine karşı mücadele göstermektir. Cemiyet, milli bilinci uyandırmak için yayın ve propaganda yollarını kullanmıştır. Kurucuları arasında Ali Münif Yeğenağa yer almaktadır.','https://tr.wikipedia.org/wiki/Kilikyalılar_Cemiyeti','Kilikyalılar Cemiyeti')
INSERT INTO datasets VALUES('52','1918','35','İstanbul'daki Rum Patrikhanesince, patrik vekilinin başkanlığında kurulmuştur.','https://www.turkcebilgi.com/yararli-milli-ve-zararli-cemiyetler-nelerdir#:~:text=b.,türediler%20grubu%20olarak%20ilan%20etmiştir.','Mavri Mira Cemiyeti')
INSERT INTO datasets VALUES('53','1918','34','1814 yılında Yunanistan'a bağımsızlığını kazandırmak amacıyla kurulmuştur (1814).','https://www.turkcebilgi.com/yararli-milli-ve-zararli-cemiyetler-nelerdir#:~:text=b.,türediler%20grubu%20olarak%20ilan%20etmiştir.','Etnik-i Eterya Cemiyeti')
INSERT INTO datasets VALUES('54','1918','61',' Doğu Karadeniz Bölgesinde faaliyet göstermiştir.','https://www.turkcebilgi.com/yararli-milli-ve-zararli-cemiyetler-nelerdir#:~:text=b.,türediler%20grubu%20olarak%20ilan%20etmiştir.','Pontus Rum Cemiyeti')
INSERT INTO datasets VALUES('55','1918','34','Filistin'den Elazığ'a kadar uzanan Büyük İsrail Devletini kurmayı amaçlamışlardır.','https://www.turkcebilgi.com/yararli-milli-ve-zararli-cemiyetler-nelerdir#:~:text=b.,türediler%20grubu%20olarak%20ilan%20etmiştir.','Alyans İsrailit Cemiyeti')
INSERT INTO datasets VALUES('56','1918','34','Wilson ilkelerinden yararlanarak doğu illerimizi içine alan bir sahada Kürt devleti kurmak amaçlanmıştır.','https://www.turkcebilgi.com/yararli-milli-ve-zararli-cemiyetler-nelerdir#:~:text=b.,türediler%20grubu%20olarak%20ilan%20etmiştir.','Kürt Teali Cemiyeti')
INSERT INTO datasets VALUES('57','1919','55','Mustafa Kemal'in Samsun'a çıkışı, 19 Mayıs 1919 tarihinde 9. Ordu Müfettişi Mustafa Kemal'in Bandırma Vapuru ile yapılan yolculuk sonrası Samsun'a ulaşması olayı. Bu olay Kurtuluş Savaşı'nın fiili başlangıcı olarak kabul edilmektedir.[1]','https://tr.wikipedia.org/wiki/Mustafa_Kemal%27in_Samsun%27a_çıkışı#:~:text=Mustafa%20Kemal%27in%20Samsun%27a%20çıkışı%2C%2019%20Mayıs%201919,fiili%20başlangıcı%20olarak%20kabul%20edilmektedir.','Mustafa Kemal'in Samsun'a çıkışı')
INSERT INTO datasets VALUES('58','1919','55','Havza'ya 25 Mayıs 1919 tarihinde giden Mustafa Kemal, İzmir'in işgalinin mitingler düzenlenerek protesto edilmesini istedi. Sonrasında Mustafa Kemal Paşa, telgraf çekilmesini de teşvik ederek yönetici olan askeri ve sivil herkese genelgeler gönderme kararı aldı. Bu genelgelerin içinde gösterilerin yapılmasını uygun bulup ancak gayrimüslim halka gösteriler esnasında kötü davranılmamasını vurguladı.','https://tr.wikipedia.org/wiki/Havza_Genelgesi','Havza Genelgesi')
INSERT INTO datasets VALUES('59','1919','5','İlk kez ulusal egemenlikten bahsedilmiştir. Bir ihtilal bildirisi niteliği taşımaktadır, çünkü İstanbul Hükümeti'ni hiçe saymakta, hükûmetin düşman devletlerin esiri olduğunu söylemekte ve milleti yine milletin kendisinin azmi ve kararlılığının kurtaracağını söylemektedir. Maddenin yorumu Türk Kurtuluş Savaşı'nın amacı ve yönetim şeklinin halk tarafından yapılması ve seçilmesidir.[1] Mustafa Kemal kendisinin hazırladığı Amasya Tamimi'ni, 9. Ordu Müfettişi sıfatı ile imzalamıştır.','https://tr.wikipedia.org/wiki/Amasya_Genelgesi','Amasya Genelgesi')
"INSERT INTO datasets VALUES('60','1919','36','Kars, Ardahan ve Batum yörelerinin işgalini önlemek amacıyla Kars İslam Şurası 
kurulmuştu. Kars İslam Şurasının öncülüğünde kongreler düzenlendi. Bu kongre lerde Türklere saldırılar düzenleyen Ermenilere karşı mücadele kararları alındı.','https://acikerisim.tbmm.gov.tr/handle/11543/1824','Kars Kongresi')"
"INSERT INTO datasets VALUES('61','1919','75','Kars, Ardahan ve Batum yörelerinin işgalini önlemek amacıyla Kars İslam Şurası 
kurulmuştu. Kars İslam Şurasının öncülüğünde kongreler düzenlendi. Bu kongre lerde Türklere saldırılar düzenleyen Ermenilere karşı mücadele kararları alındı.','https://acikerisim.tbmm.gov.tr/handle/11543/1825','Ardahan Kongresi')"
"INSERT INTO datasets VALUES('62','1919','25','Kars, Ardahan ve Batum yörelerinin işgalini önlemek amacıyla Kars İslam Şurası 
kurulmuştu. Kars İslam Şurasının öncülüğünde kongreler düzenlendi. Bu kongre lerde Türklere saldırılar düzenleyen Ermenilere karşı mücadele kararları alındı.','https://acikerisim.tbmm.gov.tr/handle/11543/1826','Oltu Kongresi')"
"INSERT INTO datasets VALUES('63','1919','61','Trabzon Muhafaza-i Hukuk Cemiyetinin öncülüğünde yapılan kongrelerde Türk 
halkının haklı davasını duyurmak için İstanbul ve Paris’e bir heyet gönderilmesi ka rarlaştırıldı. İzmir’in işgali protesto edildi ve bölgenin işgale uğraması ihtimaline karşı 
hangi önlemlerin alınacağı belirlendi. Ermeni tehdidi altındaki vilayetlerde bulunan 
millî cemiyetlerle iş birliği yapılması kararlaştırıldı','https://ataturkansiklopedisi.gov.tr/bilgi/milli-mucadele-doneminde-kongreler/','Trabzon Kongreleri')"
"INSERT INTO datasets VALUES('64','1919','25','3 Temmuz’da Erzurum’a gelen Mustafa Kemal halkın yoğun ilgisi ile karşılandı. Mustafa Kemal, Erzu rum Kongresi öncesinde İstanbul Hükûmeti’nin geri dönmesi konusundaki baskısı karşısında 8/9 Temmuz 
gecesi telgraf başında İstanbul Hükûmetine askerlik görevinden istifa ettiğini bildirdi. Mustafa Kemal bu 
durumu şöyle açıklamıştır. ','https://ataturkansiklopedisi.gov.tr/bilgi/milli-mucadele-doneminde-kongreler/','Erzurum Kongresi')"
"INSERT INTO datasets VALUES('65','1919','58','Mustafa Kemal, 2 Eylül’de Sivas’ta halkın coşkusuyla karşılandı. Sivas’ta düzenlenecek kongre, ülkenin 
bütününü temsilen toplanacaktı. Ancak kongre hazırlıkları sürerken Damat Ferit Paşa’nın başında olduğu 
İstanbul Hükûmeti Kongre'yi engellemek için harekete geçti. İstanbul Hükûmeti Elâzığ Valisi Ali Galip’e 
Mustafa Kemal’i tutuklaması yönünde emir verdi. Ancak Mustafa Kemal askerî birlikleri Ali Galip üzerine 
göndererek Kongre'yi basma teşebbüsünü engelledi.','https://ataturkansiklopedisi.gov.tr/bilgi/milli-mucadele-doneminde-kongreler/','Sivas Kongresi')"
"INSERT INTO datasets VALUES('66','1919','35','zmir’in Yunan ordusunca işgali karşısında oluşan tepki üzerine İtilaf Devlet leri kamuoyunu yatıştırmak için bölgeye Amerikalı Amiral Mark Lambert Bristol 
(Mark Lambırt Bristıl) (Görsel 2.11) başkanlığında bir heyet gönderdi.','https://ataturkansiklopedisi.gov.tr/bilgi/amiral-bristolun-rapor-ve-savas-gunlukleri/','Amiral Bristol raporu')"
"INSERT INTO datasets VALUES('67','1920','58','ABD Hükûmeti tarafından Türkiye hakkında incelemeler yapmak üzere 
görevlendirilen General James Harbord (Ceyms Harbırt) (Görsel 2.12) ve he yeti Anadolu’da incelemelerde bulundu. S','https://tr.wikipedia.org/wiki/General_Harbord_Raporu','General Harbord raporu')"
"INSERT INTO datasets VALUES('68','1919','5','Damat Ferit Paşa’nın başında olduğu İstanbul Hükûmeti Mustafa Kemal’in önderliğini yaptığı Millî 
Mücadele hareketini engellemek için büyük çaba harcıyordu. Buna rağmen genelgeler yayınlanmasını ve 
kongreler düzenlenmesini engelleyemedi.','https://tr.wikipedia.org/wiki/Amasya_Protokolü','Amasya Görüşmeleri')"
"INSERT INTO datasets VALUES('69','1920','34','Mebusan Meclisi 12 Ocak 
1920’de toplandı. Mecliste Mü dafaa-i Hukuk grubu kurulamadı 
ancak vatansever milletvekilleri 
Felah-ı Vatan (Vatanın Kurtuluşu) 
grubunu kurdular. Mustafa Kemal, 
görüştüğü milletvekillerinin söz 
vermesine rağmen, meclise başkan 
seçilemedi','https://tr.wikipedia.org/wiki/Meclis-i_Mebûsan_6._dönem_mebusları_listesi','Son Osmanlı Mebusan Meclisi')"
INSERT INTO datasets VALUES('70','1920','34','Şubat 1920’de Misak-ı Millî kararları açıklandı. Erzurum ve Sivas Kongreleri kararları doğrultusunda hazır lanan Misak-ı Millî’ye göre','https://tr.wikipedia.org/wiki/Mîsâk-ı_Millî','Misak-ı Milli Kararları')
"INSERT INTO datasets VALUES('71','1920','34','İtilaf Devletleri Misak-ı Millî kararlarının alınmasından sonra İstanbul Hükûmeti üzerindeki baskıyı ar tırdı. Ali Rıza Paşa Hükûmeti istifa etti ve Salih Paşa Hükûmeti kuruldu. 16 Mart 1920’de İstanbul resmen 
işgal edildi','https://tr.wikipedia.org/wiki/İstanbul%27un_İşgali','İstanbul'un İşgali')"
INSERT INTO datasets VALUES('72','1920','6','23 Nisan 1920 Cuma sabahı halk Meclis binası çevresinde toplandı. Halk, kendi kaderine sahip çıkma nın coşkusu içindeydi. Hacı Bayram Camii’nde kılınan cuma namazından sonra, dua edilerek M','https://tr.wikipedia.org/wiki/Türkiye_Büyük_Millet_Meclisi','Büyük Millet  Mecilisinin Açılması')
INSERT INTO datasets VALUES('73','1920','81','Düzce Ayaklanmaları, Kurtuluş Savaşı sırasında Milli Mücadele'ye karşı, 1920 yılında, Düzce'de başlayarak kısa sürede Bolu, Gerede, Mudurnu, Beypazarı ve Nallıhan'a yayılan bir dizi ayaklanma.','https://ipfs.io/ipfs/QmQP99yW82xNKPxXLroxj1rMYMGF6Grwjj2o4svsdmGh7S/out/A/Düzce_Ayaklanmaları.html#:~:text=Düzce%20Ayaklanmaları%2C%20Kurtuluş%20Savaşı%20sırasında,a%20yayılan%20bir%20dizi%20ayaklanma.','Düzce Ayaklanması')
INSERT INTO datasets VALUES('74','1920','34','Kuvâ-i İnzibâtiyye (Osmanlıca: قوا انضباطيّه; Hilafet Ordusu olarak da bilinir), Kurtuluş Savaşı'nda İstanbul Hükûmeti'nin Kuvâ-yi Milliye'ye karşı kurduğu askeri örgüt. Birleşik Krallık, Damat Ferit hükûmetine 7 Nisan 1920 tarihinde Hilafet Ordusu'nun kurulması için izin verdi. 18 Nisan tarihinde kuruldu.','https://tr.wikipedia.org/wiki/Kuvâ-yi_İnzibâtiye#:~:text=Kuvâ-i%20İnzibâtiyye%20(Osmanlıca%3A,18%20Nisan%20tarihinde%20kuruldu.','Hilafet Ordusu Ayaklanması')
INSERT INTO datasets VALUES('75','1920','42','Konya Ayaklanması, Anadolu'da Millî Mücadele'ye karşı gelişen ayaklanmalardan biridir. Diğer ayaklanmalar gibi kısa sürede bastırılmıştır. Ayaklanmayı yöneten Delibaş Mehmet'in adından dolayı Delibaş Ayaklanması olarak da bilinir.','https://tr.wikipedia.org/wiki/Konya_Ayaklanması','Delibaş Mehmet Ayaklanması')
INSERT INTO datasets VALUES('76','1920','24','Koçgiri İsyanı, Osmanlı İmparatorluğu'nun dağılmasından sonra Mart 1918-Haziran 1921 tarihleri arasında Sivas'ın Zara, İmranlı, Suşehri, Hafik, Kangal, Gürün ve Erzincan'ın Kuruçay, Kemah, Refahiye ilçesi, Tunceli'nin bazı ilçe ve köylerinde Alevi inançlı Kürt asıllı topluluğun bağımsızlık [8] için başlattığı bir ayaklanmadır. İstanbul'da bulunan Kürt Teali Cemiyeti'nin aldığı karar doğrultusunda, bağımsız bir Kürdistan kurulması için çalışmaya başlanmıştı.','https://tr.wikipedia.org/wiki/Koçgiri_İsyanı','Koçgri ayaklanması')
INSERT INTO datasets VALUES('77','1920','63','Milli Aşireti Ayaklanması (1 Haziran-8 Eylül 1920), Urfa’da yaşayan Millî aşiretinin Fransızlarla iş birliği yaparak çıkardığı ayaklanmadır. Millî kuvvetlerce bastırılmıştır.','https://tr.wikipedia.org/wiki/Milli_Aşireti_Ayaklanması#:~:text=Milli%20Aşireti%20Ayaklanması%20(1%20Haziran,Millî%20kuvvetlerce%20bastırılmıştır.&text=İsyan%20bastırıldı.','Milli Aşireti Ayaklanması')
INSERT INTO datasets VALUES('78','1920','36','1920'de Ermeni Devrimci Federasyonu gizli bir operasyon planlayarak bir suikast grubu oluşturmuştur.[51] Plan ve operasyonu yürütme ile görevlendirilen Shahan Natalie ve Soghomon Tehlirian'dır.[51','https://tr.wikipedia.org/wiki/Ermeni_isyanları#cite_note-nemesis-51','Ermeni Ayaklanması')
INSERT INTO datasets VALUES('79','1920','32','Demirci Mehmet Efe Ayaklanması, Yunan kuvvetlerinin Bursa-Uşak-Sarayköy hattına kısa sürede ulaşabilmeleri, düzenli ordunun yetersizliğine bağlanmaktadır. Ankara Hükûmeti (TBMM Hükûmeti), 9 Kasım 1920 tarihinde aldığı bir kararla Batı Cephesi'nin ikiye ayrılmasına karar vermişti.','https://tr.wikipedia.org/wiki/Demirci_Mehmet_Efe_Ayaklanması#:~:text=Demirci%20Mehmet%20Efe%20Ayaklanması%2C%20Yunan,nin%20ikiye%20ayrılmasına%20karar%20vermişti.','Demirci Mehmet Efe Ayaklanması ')
INSERT INTO datasets VALUES('80','1920','10','Ahmet Anzavur Ayaklanması (ya da Anzavur İsyanı),[3] Türk Kurtuluş Savaşı’na karşı Anadolu’da düzenlenen ayaklanmalardan biridir. İstanbul Hükümeti’nce desteklenmiş olan Anzavur Ayaklanması'nın adı, ayaklanmaya önderlik eden Anzavur Ahmet'ten gelir. Ahmet Anzavur’un önderliğinde çeşitli aralıklarla gelişen ayaklanmalar, esasen Anadolu’daki direnişi kırmaya yönelen iç isyanlar arasında en önemlisi sayılabilir. Çünkü Batı Cephesi'nin oluşturulması ve Yunanistan işgalinin durdurulmasının gecikmesine sebep olmuştur.','https://tr.wikipedia.org/wiki/Anzavur_Ayaklanması','Anzavur Ayaklanmasaı ')
INSERT INTO datasets VALUES('81','1920','66','Yozgat Ayaklanması veya Çapanoğlu Ayaklanması, Türk Kurtuluş Savaşı sırasında Hürriyet ve İtilaf reisi Çapanoğlu Edip Bey ve kardeşi Celâl Bey tarafından Yozgat ve yöresinde çıkarılan ayaklanmadır.','https://tr.wikipedia.org/wiki/Yozgat_Ayaklanması','Çapanoğlu Ayaklanması ')
"INSERT INTO datasets VALUES('82','1920','6','Hıyanet-i Vataniye (Vatana İhanet) Kanunu Meclis’te kabul edilerek isyana karışanlar vatan haini kabul edildi 
(29 Nisan 1920).','https://tr.wikipedia.org/wiki/Hıyanet-i_Vataniye_Kanunu','Hıyanet-i Vataniye Kanunu')"
INSERT INTO datasets VALUES('83','1920','6','• İstiklal Mahkemeleri kurularak Hıyanet-i Vataniye Kanunu'nda belirtilen suçları işleyenler yargılanma ya başlandı (11 Eylül 1920).','https://tr.wikipedia.org/wiki/İstiklâl_mahkemesi','İstiklal Mahkemeleri')
INSERT INTO datasets VALUES('84','1920','6','Anadolu Ajansı'nın tarihi, Türkiye Cumhuriyeti'nin tarihi ile adeta özdeştir. Türkiye Büyük Millet Meclisi açılmadan 17 gün önce 6 Nisan 1920'de kurulan Anadolu Ajansı, TBMM'nin çıkardığı ilk yasaları duyurdu; Milli Mücadele'nin ve Kurtuluş Savaşı'nın her aşamasına, Cumhuriyet devrimlerine tanıklık etti.','https://www.aa.com.tr/tr/p/tarihce#:~:text=Anadolu%20Ajansı%27nın%20tarihi%2C%20Türkiye,aşamasına%2C%20Cumhuriyet%20devrimlerine%20tanıklık%20etti.','Anadolu Ajansı'nın kurulması')
INSERT INTO datasets VALUES('85','1920','34','Sevr Antlaşması (Fransızca: Le Traité de Sèvres), I. Dünya Savaşı sonrasında İtilâf Devletleri ile Osmanlı İmparatorluğu hükûmeti arasında 10 Ağustos 1920'de Fransa'nın başkenti Paris'in 3 km batısındaki Sevr (Sèvres) banliyösünde bulunan Seramik Müzesi'nde (Musée National de Céramique) imzalanmış antlaşmadır. Antlaşma imzalandığı dönemde devam eden Türk Kurtuluş Savaşı'nın sonucunda Türklerin galibiyetiyle, bu antlaşma yerine 24 Temmuz 1923'te Lozan Antlaşması imzalanıp uygulamaya konulduğundan Sevr Antlaşması geçerliliğini kaybetmiştir. Sevr Antlaşması 433 maddeden oluşmaktaydı.[1]','https://tr.wikipedia.org/wiki/Sevr_Antlaşması','Sevr Antlaşması')
INSERT INTO datasets VALUES('86','1920','76','Gümrü Antlaşması, Türk Kurtuluş Savaşı sırasında Türkiye Büyük Millet Meclisi Hükümeti ile Ermenistan Demokratik Cumhuriyeti arasında 3 Aralık 1920'de imzalanan antlaşmadır. Ayrıca TBMM'nin uluslararası alanda imzaladığı ilk antlaşmadır.','https://tr.wikipedia.org/wiki/Gümrü_Antlaşması','Gümrü Antlaşması')
INSERT INTO datasets VALUES('87','1920','46','Maraş Muharebesi, I. Dünya Savaşı'nda yenilmesi üzerine, Osmanlı İmparatorluğu ile 30 Ekim 1918'de imzalanan Mondros Mütarekesi[1] çerçevesinde Anadolu'nun birçok yeri gibi Maraş'ın da işgal altına girmesi ile işgal güçlerine karşı 21 Ocak 1920'de başlayan direniş, 12 Şubat 1920 tarihinde işgalin ortadan kalkması ile sonuçlanmıştır.','https://tr.wikipedia.org/wiki/Maraş_Muharebesi','Maraş Savunması')
INSERT INTO datasets VALUES('88','1920','63','Ekim 1919'da İngilizlerden sonra Urfa'ya giren Fransızlar burada da Maraş'takine benzer uygulamalarda bulunmuşlardır. Bununla yetinmeyerek, Haçlı Seferleri sırasında kurulan Urfa Haçlı Kontluğu'na kadar geriye giden birtakım haklar ileri sürmüşlerdir.','https://tr.wikipedia.org/wiki/Urfa_Muharebesi','Urfa Savunması')
INSERT INTO datasets VALUES('89','1921','27','Antep Kuşatması, Kuvâ-yi Milliye ile Fransa arasında gerçekleşen, Kuvâ-yi Milliye'nin 10 ay süren direnişinin ardından 9 Şubat 1921 tarihinde şehrin Fransızların eline geçmesiyle sonuçlanan kuşatma. Kuşatma sırasında Fransız ordusunun 70.000-80.000 kadar top mermisi ile şehri bombardımana tutması sonucu 8.000 bina harap oldu ve bir o kadar bina da hasar gördü.','https://tr.wikipedia.org/wiki/Antep_Kuşatması','Antep Savunması')
"INSERT INTO datasets VALUES('90','1921','1','Mondros Ateşkes Anlaşması’nın imzalanmasından sonra Fransızlar; Maraş, Urfa, Antep ve Adana’yı da işgal etmişti.

Adana’da güvenlik örgütünün yönetimine bir Ermeni’yi müdür olarak atadılar. Bu müdürün yönetiminde kısa sürede Türklere karşı baskı ve zulüm başlatan Ermeniler, bölgede birçok tarım alanı ve köyü basarak yakıp yıktılar.','https://www.fikir.gen.tr/adana-savunmasi/','Adana Savunması')"
INSERT INTO datasets VALUES('91','1919','35','İzmir'in İşgali, I. Dünya Savaşı sonrasında Paris'te toplanan uluslararası barış konferansının kararıyla[kaynak belirtilmeli] İzmir kentinin 15 Mayıs 1919'da Yunanistan Krallığı tarafından işgaliyle başlayan ve 9 Eylül 1922'de Türk ordusunun kente girmesiyle sona eren işgaldir.','https://tr.wikipedia.org/wiki/İzmir%27in_İşgali','İzmir'in İşgali')
INSERT INTO datasets VALUES('92','1921','26','I. İnönü Muharebesi, 6 Ocak 1921 tarihinde iki koldan taarruza geçen Yunan kuvvetleriyle İnönü mevzilerinde savunmada olan Ankara Hükümeti kuvvetleri arasında yapılan muharebedir. 6 Ocak 1921 tarihine kadar Uşak ve Bursa bölgesinde hazırlıklarını sürdüren Yunanlar, Türk-Batı Cephesi birliklerinin Çerkez Ethem Kuvvetlerinin Tenkili harekâtı ile meşgul olmasından da faydalanarak, İnönü-Eskişehir istikametinde taarruza başladılar.','https://tr.wikipedia.org/wiki/Birinci_İnönü_Muharebesi','I. İnönü Muharabesi')
INSERT INTO datasets VALUES('93','1921','6','Teşkilat-ı Esasiye Kanunu (Osmanlı Türkçesi: تشکیلات اساسیه قانونى) veya 1921 Anayasası, 1924 Anayasası'nın ilkelerini belirlemiş; 85 numaralı ve kabul tarihi 20 Kânun-ı Sani 1337 (20 Ocak 1921) olan 23 madde ve bir ayrık maddeden oluşan kısa ve "çerçeve anayasa" niteliğinde bir belgedir.','https://tr.wikipedia.org/wiki/Teşkîlât-ı_Esâsiye_Kanunu','Teşkilat-ı Esasiye Kanunu')
"INSERT INTO datasets VALUES('94','1921','6','İstiklâl Marşı (Osmanlıca: استقلال مارشى), Türkiye ve Kuzey Kıbrıs Türk Cumhuriyeti'nin[2] millî marşı.

Güftesi, Anadolu'da Millî Mücadele'nin devam ettiği sırada Mehmet Âkif Ersoy tarafından kaleme alınmış şiirdir. Şairin Kurtuluş Savaşı'nın kazanılacağına olan inancını, Türk askerinin yürekliliğine ve özverisine güvenini, Türk ulusunun bağımsızlığa, Hakk'a, yurduna ve dinine bağlılığını dile getirir.','https://tr.wikipedia.org/wiki/İstiklâl_Marşı','İstiklal Marşı'nın kabulü')"
"INSERT INTO datasets VALUES('95','1921','43','Kütahya-Eskişehir Muharebeleri, 10 Temmuz 1921 ile 24 Temmuz 1921 tarihleri arasında Yunanistan ile Ankara Hükûmeti ordusu arasında gerçekleşen muharebelerdir. Muharebeleri kaybeden Ankara Hükûmeti kuvvetleri Sakarya Nehri'nin doğusuna çekilmek zorunda kaldı.


','https://tr.wikipedia.org/wiki/Kütahya-Eskişehir_Muharebeleri','Kütahya-Eskişehir Muharebeleri')"
INSERT INTO datasets VALUES('96','1921','6','1921 yılında Ankara’da toplanan Maarif Kongresi’nin eğitim tarihimiz içinde önemli bir yeri vardır. Bu kongre okul ve öğrenci mevcudunu tespit etmek, bu konuda yapılması gereken çalışmaları belirlemek ve eğitime millî bir yön vermek amacıyla toplanmıştır.','https://dergipark.org.tr/tr/pub/yalovasosbil/issue/21791/615860','Maarif Kongresi')
INSERT INTO datasets VALUES('97','1921','6','Tekâlif-i Milliye (Millî Yükümlülükler ya da Ulusal Vergiler), Türk Kurtuluş Savaşı'nın dönüm noktalarından olan Sakarya Meydan Muharebesi öncesi ordunun ihtiyacını karşılamak ve Sakarya Savaşı'na hazırlanmak için Başkomutan Mustafa Kemal Paşa'nın kanunla kendisine verilen yasama yetkisini kullanarak yayınladığı "Ulusal Yükümlülük" emirleridir. 7 Ağustos 1921'de yayınlanmış olup toplamı on maddedir.','https://tr.wikipedia.org/wiki/Tekâlif-i_Milliye','Tekalif-iMilliye Emirleri')
INSERT INTO datasets VALUES('98','1921','6','Sakarya Meydan Muharebesi, Atatürk tarafından çok büyük ve kanlı savaş anlamına gelen Melhame-i Kübra ifadesi ile anılan, Türk Kurtuluş Savaşı'nın önemli bir muharebesi.','https://tr.wikipedia.org/wiki/Sakarya_Meydan_Muharebesi','Sakarya Meydan Muharebesi')
INSERT INTO datasets VALUES('99','1921','36','Kars Antlaşması, Rusya, 1917'den sonra Kafkasya’dan çekildi. Bölgede Azerbaycan, Gürcistan ve Ermenistan bağımsızlığına kavuşmuş ve Azerbaycan Demokratik Cumhuriyeti, Gürcistan Demokratik Cumhuriyeti, Ermenistan Demokratik Cumhuriyeti adında üç devlet kurulmuştur. Fakat Rusya Sovyet Federatif Sosyalist Cumhuriyeti iki yıl sonra Kafkasya’yı yeniden işgal etmiştir. Bölgedeki üç devlet Sovyetler Birliği ismini alan yeni Sovyet rejiminin idaresine girdi. Sakarya Muharebesinin Ankara Hükûmetinin zaferiyle sonuçlanmasından sonra Sovyet Rusya’nın aracılığıyla üç Sovyet Cumhuriyeti Azerbaycan, Gürcistan ve Ermenistan ile Kâzım Karabekir'in temsil ettiği TBMM Hükûmeti arasında 13 Ekim 1921'de Kars Antlaşması imzalandı.','https://tr.wikipedia.org/wiki/Kars_Antlaşması','Kars Antlaşması')
INSERT INTO datasets VALUES('100','1921','3','Büyük Taarruz, Türk Kurtuluş Savaşı sırasında Türk ordusunun Yunan kuvvetlerine karşı başlattığı genel saldırıdır. Bakanlar Kurulu taarruz kararını almış ve 14 Ağustos 1922 tarihinde kolordular taarruz için yürüyüşe geçmiş, 26 Ağustos'ta saldırı başlamış, 9 Eylül'de Türk Ordusu İzmir'e girmiş ve 18 Eylül'de de Yunan Ordusu'nun Anadolu'yu tamamen terk etmesiyle savaş sona ermiştir.','https://tr.wikipedia.org/wiki/Büyük_Taarruz','Büyük Taaruz')
INSERT INTO datasets VALUES('101','1921','43','Başkomutanlık Meydan Muharebesi ya da Dumlupınar Meydan Muharebesi, Kütahya'ya bağlı Dumlupınar yakınında 30 Ağustos 1922'de Türk ve Yunan orduları arasında meydana gelen savaştır. Başkomutan Mustafa Kemal Paşa tarafından şahsen yönetildiği için Başkomutanlık Meydan Muharebesi olarak anılır. İstiklal Savaşı'nın kesin bir Türk zaferiyle sonuçlanmasını sağlayan bu çarpışmanın yıldönümü Türkiye'de ulusal bayram olarak kutlanmaktadır.','https://tr.wikipedia.org/wiki/Başkomutanlık_Meydan_Muharebesi','Başkomutanlık Meydan Muharebesi')
INSERT INTO datasets VALUES('102','1922','16','Mudanya Mütârekesi veya Mudanya Ateşkes Antlaşması, Kurtuluş Savaşı'nın sonunda imzalanan mütarekedir. Osmanlı İmparatorluğu bu mütarekeyle beraber hukuken sona erdi.','https://tr.wikipedia.org/wiki/Mudanya_Mütarekesi','Mudanya Ateşkes Antlaşması')
INSERT INTO datasets VALUES('103','1923','6','Lozan Antlaşması (veya yapıldığı dönem Türkçesi ile Lozan Sulh Muâhedenâmesi), 24 Temmuz 1923 tarihinde İsviçre'nin Lozan şehrinde, Türkiye Büyük Millet Meclisi temsilcileriyle Britanya İmparatorluğu, Fransız Cumhuriyeti, İtalya Krallığı, Japon İmparatorluğu, Yunanistan Krallığı, Romanya Krallığı ve Sırp, Hırvat ve Sloven Krallığı (Yugoslavya) temsilcileri tarafından, Leman Gölü kıyısındaki Beau-Rivage Palace'ta imzalanmış barış antlaşması.','https://tr.wikipedia.org/wiki/Lozan_Antlaşması','Lozan Barış Antlaşması')
INSERT INTO datasets VALUES('104','1923','6','Cumhuriyetin ilanı, hukuksal olarak İkinci Dönem Türkiye Büyük Millet Meclisinin 29 Ekim 1923 günü gerçekleşen oturumunda Mustafa Kemal'in hazırladığı anayasa değişikliği teklifinin kabul edilmesiyle Türkiye Devleti'nin yönetim şeklinin cumhuriyet olarak belirlenmesidir.','https://tr.wikipedia.org/wiki/Türkiye%27de_cumhuriyetin_ilanı','Cumhuriyetin İlanı')
